enyo.depends(
	"css/CustomKinds.css",
	"css/HomeControl.css",
	"source/CustomKinds.js",
	"source/HomeControl.js",
	"source/Startup.js",
	"source/extensions/MediaCenter.js",
	"source/extensions/MusicPlayer.js",
	"source/extensions/VideoPlayer.js",
	"source/extensions/StatusInfo.js",
	"source/extensions/Surveillance.js",
	"source/extensions/SystemInput.js",
	"source/extensions/SystemSound.js",
	"source/extensions/UPnPController.js",
	"source/extensions/UPnPSpeaker.js",
	"source/extensions/UPnPTV.js",
	"$enyo-lib/mediacapture/"
);
